name: Continuous Integration

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Repo
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Building Repo
      run: ./gradlew build
